"""Credential-free, durable sales ledger for NV automation.

Jobs are execution state, not orders. Only the persisted, cycle-verified NV
sale evidence may open an order. Account deletion and task cleanup never cascade
into this ledger. Money is stored as integer CNY cents. Once the frozen warranty
deadline passes, the frozen listing price becomes the received amount unless an
operator supplied an explicit override (including zero). Mother costs remain
explicit operator entries; listing prices are never read from current settings.
Verified NV buyer refunds take precedence over both amounts without erasing
the original order or its manual financial audit trail.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal

from sqlalchemy import inspect
from sqlalchemy.orm import object_session
from sqlmodel import Field, Session, SQLModel, select

from services.nv_refunds import NvSaleRefund, refund_for_order, refunds_for_orders


class NvSaleOrder(SQLModel, table=True):
    __tablename__ = "nv_sale_orders"
    id: str = Field(default_factory=lambda: uuid.uuid4().hex, primary_key=True)
    sale_key: str = Field(unique=True, index=True)
    job_id: str = Field(unique=True, index=True)
    parent_account_id: int = Field(index=True)
    source_account_id: int = 0
    parent_email: str
    parent_note: str = ""
    child_id: int | None = None
    email: str = Field(index=True)
    membership_id: int | None = None
    seat_type: str = ""
    nv_order_id: str = Field(default="", index=True)
    nv_card_id: str = Field(default="", index=True)
    listed_at: str = ""
    sold_at: str = Field(index=True)
    warranty_until: str = ""
    left_at: str = ""
    listing_price_cents: int | None = None
    revenue_cents: int | None = None
    revenue_source: str = "unknown"
    finance_note: str = ""
    # Financial optimistic lock: unrelated lifecycle updates don't lose edits.
    version: int = 0
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)


class NvMotherCost(SQLModel, table=True):
    __tablename__ = "nv_mother_costs"
    parent_account_id: int = Field(primary_key=True)
    parent_email: str
    parent_note: str = ""
    cost_cents: int | None = None
    cost_note: str = ""
    version: int = 0
    updated_at: float = Field(default_factory=time.time)


class NvFinanceRevision(SQLModel, table=True):
    __tablename__ = "nv_finance_revisions"
    id: int | None = Field(default=None, primary_key=True)
    entity_type: str
    entity_id: str = Field(index=True)
    before_json: str
    after_json: str
    created_at: float = Field(default_factory=time.time)


MODELS = (NvSaleOrder, NvMotherCost, NvFinanceRevision, NvSaleRefund)
# Current-day accounting uses Beijing time regardless of the server's timezone.
# UTC+8 also works on deployments without a system IANA timezone database.
_REVENUE_TIMEZONE = timezone(timedelta(hours=8), "Asia/Shanghai")
_REFUND_UNSET = object()


def _store():
    from services import nv_automation_store
    return nv_automation_store


def _date(value):
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        result = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
        # Older evidence was generated by the UTC-naive project clock.
        return result.replace(tzinfo=timezone.utc) if result.tzinfo is None else result.astimezone(timezone.utc)
    except (ValueError, OverflowError):
        return None


def _iso(value):
    return value.isoformat() if value is not None else ""


def _timestamp(value):
    return datetime.fromtimestamp(value, timezone.utc).isoformat()


def parse_money(value):
    """None means unknown. An explicit zero is a valid recorded amount."""
    if value is None:
        return None
    if not isinstance(value, str) or not re.fullmatch(r"\d{1,9}(?:\.\d{1,2})?", value.strip()):
        raise ValueError("金额必须为非负人民币金额，最多两位小数")
    return int(Decimal(value.strip()) * 100)


def _money(cents):
    return None if cents is None else f"{Decimal(cents) / 100:.2f}"


def _identifier(value):
    if not isinstance(value, str):
        return ""
    value = value.strip()
    return value if re.fullmatch(r"[A-Za-z0-9_.:-]{1,160}", value) and _store().safe_message(value) == value else ""


def _note(value):
    if not isinstance(value, str) or len(value) > 500:
        raise ValueError("备注最多 500 字")
    return _safe_note(value)


def _safe_note(value):
    # Strip compound headers BEFORE generic key=value redaction; otherwise
    # replacing just "Basic" or the first cookie leaks the remaining payload.
    value = re.sub(r"(?i)\b(?:proxy-authorization|authorization)\b\s*['\"]?\s*[:=：]\s*(?:Basic|Bearer)\s+[^\r\n,;]+",
                   "Authorization=[已隐藏]", str(value or ""))
    value = re.sub(r"(?i)\b(?:set-cookie|cookie|cookies)\b\s*['\"]?\s*[:=：][^\r\n]+", "Cookie=[已隐藏]", value)
    return _store().safe_message(value.strip())[:500]


def _mother_catalog(session, ids):
    """Project display fields only; never SELECT an account's credentials."""
    if not ids or not inspect(session.connection()).has_table("gpt_plan_accounts"):
        return {}
    from types import SimpleNamespace
    from core.db import GptPlanAccountModel as Account, GptBusinessAccountModel as Mother
    from services.business_mother_status import mother_dead_status
    rows = session.exec(select(Account.id, Account.email, Account.note, Account.dangerous,
        Account.dangerous_detected_at, Account.source_pool, Account.source_account_id)
        .where(Account.id.in_(ids))).all()
    source_ids = {row[6] for row in rows if row[5] == "gpt_business" and row[6]}
    sources = {}
    if source_ids and inspect(session.connection()).has_table(Mother.__tablename__):
        sources = {row[0]: row for row in session.exec(select(Mother.id, Mother.email,
            Mother.dangerous, Mother.dangerous_detected_at).where(Mother.id.in_(source_ids))).all()}
    catalog = {}
    for row in rows:
        source = sources.get(row[6]) if row[5] == "gpt_business" else None
        # A stale/reused source binding cannot assign another account's DEAD stamp.
        source_status = (SimpleNamespace(dangerous=source[2], dangerous_detected_at=source[3])
                         if source and source[1].strip().casefold() == row[1].strip().casefold() else None)
        catalog[row[0]] = {"email": row[1], "note": _safe_note(row[2]),
            **mother_dead_status(SimpleNamespace(dangerous=row[3], dangerous_detected_at=row[4]), source_status)}
    return catalog


def _absolute_warranty(ctx):
    """Only the submitted/adopted contract can define a fixed 5X deadline."""
    from services.nv_listing_warranty import normalize_team5x_warranty
    frozen = normalize_team5x_warranty(ctx.get("team5x_warranty"), require_future=False)
    deadline = _date(frozen["until"]) if frozen else None
    basis = ctx.get("existing_listing")
    if isinstance(basis, dict):
        raw = basis.get("nv_team5x_warranty_until")
        original = _date(raw)
        if (raw and original is None) or (deadline is not None and deadline != original):
            raise ValueError("接管订单的 5X 质保截止时间不一致")
        deadline = original
    return deadline


def _frozen_cycle(job, ctx, listed):
    basis = ctx.get("existing_listing")
    if basis is not None:
        if not isinstance(basis, dict) or ctx.get("existing_member") is not True or basis.get("kind") != "persisted_nv_listing":
            return False
        if any(basis.get(key) != getattr(job, key) for key in
               ("parent_account_id", "source_account_id", "child_id", "email", "membership_id", "remote_user_id")):
            return False
        invited, original, confirmed = (_date(basis.get(key)) for key in
            ("membership_invited_at", "nv_listed_at", "nv_listing_confirmed_at"))
        hours = basis.get("warranty_hours")
        absolute = _date(basis.get("nv_team5x_warranty_until"))
        return bool(invited and original == listed and confirmed and invited <= listed <= confirmed
                    and _identifier(basis.get("remote_user_id")) and basis.get("identifiers_valid") is not False
                    and ((absolute is not None and absolute > listed)
                         or (type(hours) is int and 1 <= hours <= 87600)))
    baseline = ctx.get("publish_baseline")
    started = _date(ctx.get("publish_started_at"))
    captured = _date(baseline.get("captured_at")) if isinstance(baseline, dict) else None
    return bool(ctx.get("publish_attempted") is True and isinstance(baseline, dict)
                and baseline.get("clear") is True and isinstance(baseline.get("email"), str)
                and baseline["email"].casefold() == job.email.casefold()
                and captured and started and captured <= started <= listed)


def _evidence(job):
    ctx = _store()._decode(job.context_json)
    sold, listed = _date(ctx.get("sold_at")), _date(ctx.get("nv_listed_at"))
    confirmed = _date(ctx.get("nv_listing_confirmed_at"))
    checked = _date(ctx.get("nv_last_synced_at"))
    warranty = _date(ctx.get("warranty_until"))
    card, order = _identifier(ctx.get("nv_remote_card_id")), _identifier(ctx.get("nv_remote_order_id"))
    if any(ctx.get(key) and not _identifier(ctx[key]) for key in ("nv_remote_card_id", "nv_remote_order_id")):
        return None
    # Importing an existing manually marked sold membership does not set these
    # verification timestamps; _persist_evidence only does so after full NV
    # pagination, cycle, identity and sale-time checks succeed.
    if (ctx.get("publish_confirmed") is not True or not sold or not listed or
            not checked or not confirmed or not warranty or not (card or order) or
            not listed <= sold <= checked or not listed <= confirmed <= checked or warranty < sold or
            checked > datetime.now(timezone.utc) or type(job.membership_id) is not int or job.membership_id <= 0 or
            type(job.parent_account_id) is not int or job.parent_account_id <= 0 or
            not re.fullmatch(r"[^\s@]{1,200}@[^\s@]{1,119}", job.email or "") or
            not re.fullmatch(r"[^\s@]{1,200}@[^\s@]{1,119}", job.parent_email or "") or
            not _frozen_cycle(job, ctx, listed)):
        return None
    basis = ctx.get("existing_listing")
    hours = basis.get("warranty_hours") if isinstance(basis, dict) else ctx.get("warranty_hours", 1)
    try:
        absolute = _absolute_warranty(ctx)
    except ValueError:
        return None
    warranty_valid = (absolute > listed and warranty == absolute if absolute is not None
                      else type(hours) is int and 1 <= hours <= 87600 and warranty == sold + timedelta(hours=hours))
    if (not warranty_valid or
            (isinstance(basis, dict) and _date(basis.get("nv_listing_confirmed_at")) != confirmed)):
        return None
    identity = ctx.get("nv_card_identity")
    if identity is not None and not isinstance(identity, dict):
        return None
    card_aliases = {card} if card else set()
    if isinstance(identity, dict):
        keys = {"kind", "email", "listing_started_at", "sold_at", "inventory_card_id", "order_card_id", "remote_order_id"}
        if (set(identity) != keys or identity.get("kind") != "nv_card_identity_v1" or
                identity.get("email") != job.email.strip().casefold() or
                _date(identity.get("listing_started_at")) != listed or
                any(not _identifier(identity.get(key)) or _identifier(identity[key]) != identity[key]
                    for key in ("inventory_card_id", "order_card_id", "remote_order_id"))):
            return None
        canonical = _identifier(identity.get("order_card_id"))
        if (canonical and card in {canonical, _identifier(identity.get("inventory_card_id"))} and
                _identifier(identity.get("remote_order_id")) == order and _date(identity.get("sold_at")) == sold):
            card_aliases.update({canonical, _identifier(identity.get("inventory_card_id"))})
            card = canonical
        else:
            return None
    basis = ctx.get("existing_listing")
    if isinstance(basis, dict):
        if any(basis.get(key) and not _identifier(basis[key]) for key in ("nv_remote_card_id", "nv_remote_order_id")):
            return None
        frozen_order = _identifier(basis.get("nv_remote_order_id"))
        frozen_card = _identifier(basis.get("nv_remote_card_id"))
        if (frozen_order and frozen_order != order) or (frozen_card and frozen_card not in card_aliases):
            return None
    try:
        listing_price = parse_money(ctx.get("price_yuan")) if ctx.get("publish_attempted") is True else None
    except ValueError:
        listing_price = None
    # Explicit NV repricing must be confirmed while the same card is still
    # available and before its sale. Global defaults never rewrite receipts.
    repriced = ctx.get("nv_price_confirmed")
    if isinstance(repriced, dict):
        checked = _date(repriced.get("confirmed_at"))
        cycle = _date(repriced.get("listing_started_at"))
        if (checked and listed <= checked <= sold and cycle == listed
                and _identifier(repriced.get("card_id")) in card_aliases):
            try:
                listing_price = parse_money(repriced.get("price_yuan"))
            except ValueError:
                pass
    if ctx.get("nv_price_sale_unverified") is True:
        # A card sold between the PATCH and readback: neither old nor new
        # listing price is reliable sale evidence. Do not fabricate revenue.
        listing_price = None
    email = job.email.strip().lower()
    # Identity is rooted in NV, never email, ownership or mutable timestamps.
    # An order may contain multiple distinct cards. Card-only and order-only
    # evidence can later be enriched without opening another receipt.
    identity_key = ["nv-order-card", order, card] if order and card else (
        ["nv-order", order] if order else ["nv-card", card])
    key = hashlib.sha256(json.dumps(identity_key, separators=(",", ":")).encode()).hexdigest()
    left = _date(ctx.get("left_at")) if job.status == "completed" and job.step == "done" else None
    if left and (left < sold or left > datetime.now(timezone.utc)):
        left = None
    return dict(sale_key=key, email=email, listed_at=_iso(listed), sold_at=_iso(sold),
                warranty_until=_iso(warranty), nv_card_id=card, nv_order_id=order,
                listing_price_cents=listing_price, left_at=_iso(left), card_aliases=card_aliases - {""})


def sync_order(session, job):
    """Idempotent, local-only write inside the caller's fenced transaction."""
    evidence = _evidence(job)
    if evidence is None:
        return None
    aliases = evidence.pop("card_aliases")
    match = ((NvSaleOrder.sale_key == evidence["sale_key"]) | (NvSaleOrder.job_id == job.id) |
             ((NvSaleOrder.email == evidence["email"]) & (NvSaleOrder.sold_at == evidence["sold_at"])))
    if aliases:
        match |= NvSaleOrder.nv_card_id.in_(aliases)
    if evidence["nv_order_id"]:
        same_order = NvSaleOrder.nv_order_id == evidence["nv_order_id"]
        match |= same_order & ((NvSaleOrder.nv_card_id.in_(aliases)) | (NvSaleOrder.nv_card_id == "")) if aliases else same_order
    existing = session.exec(select(NvSaleOrder).where(match)).all()
    if existing:
        if len(existing) != 1:
            return None
        order = existing[0]
        # Freeze attribution and the sale cycle, including deletion/restart and
        # a duplicate discovery. Never reassign a historical receipt by email.
        if (order.parent_account_id != job.parent_account_id or
                order.source_account_id != job.source_account_id or order.membership_id != job.membership_id or
                order.parent_email.casefold() != job.parent_email.strip().casefold() or
                order.email != evidence["email"] or order.listed_at != evidence["listed_at"] or
                order.sold_at != evidence["sold_at"] or
                (order.nv_card_id and evidence["nv_card_id"] and order.nv_card_id not in aliases) or
                (order.nv_order_id and evidence["nv_order_id"] and order.nv_order_id != evidence["nv_order_id"])):
            return None
        changed = False
        for name in ("nv_order_id", "nv_card_id", "left_at"):
            if not getattr(order, name) and evidence[name]:
                setattr(order, name, evidence[name])
                changed = True
        if changed:
            order.updated_at = time.time()
            session.add(order)
        _sync_refund(session, job)
        return order
    catalog = _mother_catalog(session, [job.parent_account_id]).get(job.parent_account_id, {})
    parent_note = catalog.get("note", "") if catalog.get("email", "").casefold() == job.parent_email.casefold() else ""
    order = NvSaleOrder(**evidence, job_id=job.id, parent_account_id=job.parent_account_id,
        source_account_id=job.source_account_id, parent_email=job.parent_email.strip(), parent_note=parent_note,
        child_id=job.child_id, membership_id=job.membership_id,
        seat_type=job.seat_type if job.seat_type in {"default", "prolite"} else "")
    session.add(order)
    session.flush()
    _sync_refund(session, job)
    return order


def _sync_refund(session, job):
    proof = _store()._decode(job.context_json).get("nv_refund")
    if proof is not None:
        from services.nv_refunds import record_refund
        record_refund(session, job, proof)


def backfill():
    """Use stored strong evidence only. No NV requests and no task execution."""
    store = _store()
    # Very old/minimal schemas may not yet carry identity/evidence columns.
    # create_all doesn't add them: lack of data is not permission to invent it,
    # nor should this optional financial migration block ordinary startup.
    columns = {item["name"] for item in inspect(store.engine).get_columns("nv_automation_jobs")}
    if not set(store.NvAutomationJob.__table__.columns.keys()).issubset(columns):
        return 0
    with store.transaction() as session:
        before = len(session.exec(select(NvSaleOrder.id)).all())
        for job in session.exec(select(store.NvAutomationJob).order_by(store.NvAutomationJob.created_at)).all():
            sync_order(session, job)
        session.flush()
        return len(session.exec(select(NvSaleOrder.id)).all()) - before


def _resolve_refund(order, refund):
    if refund is not _REFUND_UNSET:
        return refund
    session = object_session(order) if isinstance(order, NvSaleOrder) else None
    return refund_for_order(session, order) if session is not None else None


def _receipt(order, now=None, *, refund=_REFUND_UNSET):
    """Derive the receipt from frozen order facts without mutating the ledger.

    NV confirms the sale cycle, while the frozen warranty deadline determines
    when that sale counts as received.  ``revenue_cents`` is deliberately kept
    as the operator's override except when verified buyer-refund evidence
    supersedes it. Partial refunds never guess supplier proceeds from list price.
    """
    now = now or datetime.now(timezone.utc)
    warranty = _date(order.warranty_until)
    refund = _resolve_refund(order, refund)
    if refund is not None:
        if refund["full_refund"]:
            return dict(status="refunded", received_at=None, revenue_cents=0, revenue_source="nv_refund")
        matured = warranty is not None and warranty <= now
        net = refund["supplier_amount_cents"] if matured else None
        return dict(status="partial_refund", received_at=_iso(warranty) if matured else None,
                    revenue_cents=net, revenue_source="nv_supplier_net" if net is not None else "unknown",
                    pending_warranty=bool(warranty and warranty > now))
    # Manual-sale orders have no NV warranty contract.  Once an operator has
    # explicitly recorded both the amount and the space exit, the exit time is
    # the auditable settlement time and the order counts as received.
    if (warranty is None and order.revenue_source == "manual"
            and order.revenue_cents is not None and _date(order.left_at) is not None):
        settled_at = _date(order.left_at)
        return {
            "status": "received",
            "received_at": _iso(settled_at),
            "revenue_cents": order.revenue_cents,
            "revenue_source": "manual",
        }
    if warranty is None:
        return {
            "status": "unknown",
            "received_at": None,
            "revenue_cents": None,
            "revenue_source": "unknown",
        }
    if warranty > now:
        return {
            "status": "pending_warranty",
            "received_at": None,
            "revenue_cents": None,
            "revenue_source": "unknown",
        }
    if order.revenue_cents is not None:
        revenue_cents, source = order.revenue_cents, "manual"
    elif order.listing_price_cents is not None:
        revenue_cents, source = order.listing_price_cents, "warranty_expired"
    else:
        revenue_cents, source = None, "unknown"
    return {
        "status": "received",
        "received_at": _iso(warranty),
        "revenue_cents": revenue_cents,
        "revenue_source": source,
    }


def _received(receipt):
    return receipt["status"] == "received" or (receipt["status"] == "partial_refund" and receipt["received_at"] is not None)


def _pending(receipt):
    return receipt["status"] == "pending_warranty" or receipt.get("pending_warranty", False)


def _public(order, now=None, *, refund=_REFUND_UNSET):
    now = now or datetime.now(timezone.utc)
    warranty = _date(order.warranty_until)
    refund = _resolve_refund(order, refund)
    receipt = _receipt(order, now, refund=refund)
    lifecycle = "closed" if order.left_at else ("in_warranty" if warranty and warranty > now else "awaiting_exit")
    return dict(id=order.id, job_id=order.job_id, parent_account_id=order.parent_account_id,
        parent_email=order.parent_email, parent_note=order.parent_note, child_id=order.child_id,
        email=order.email, membership_id=order.membership_id, seat_type=order.seat_type,
        nv_order_id=order.nv_order_id, nv_card_id=order.nv_card_id, listed_at=order.listed_at or None,
        sold_at=order.sold_at, warranty_until=order.warranty_until or None, left_at=order.left_at or None,
        lifecycle_status=lifecycle, listing_price_yuan=_money(order.listing_price_cents),
        receipt_status=receipt["status"], received_at=receipt["received_at"],
        revenue_yuan=_money(receipt["revenue_cents"]), revenue_source=receipt["revenue_source"],
        refund_status=("full" if refund["full_refund"] else "partial") if refund else "none",
        refunded_at=refund["refunded_at"] if refund else None,
        refund_amount_yuan=_money(refund["refund_amount_cents"]) if refund else None,
        sale_amount_yuan=_money(refund["amount_cents"]) if refund else None,
        supplier_amount_yuan=_money(refund["supplier_amount_cents"]) if refund else None,
        refund_verified_at=refund["verified_at"] if refund else None,
        finance_note=order.finance_note, version=order.version,
        created_at=_timestamp(order.created_at), updated_at=_timestamp(order.updated_at))


def list_orders(q="", parent_account_id=None, page=1, page_size=50):
    page, page_size = max(1, int(page)), max(1, min(100, int(page_size)))
    with Session(_store().engine) as session:
        query = select(NvSaleOrder)
        if parent_account_id is not None:
            query = query.where(NvSaleOrder.parent_account_id == int(parent_account_id))
        if q.strip():
            term = "%" + q.strip().replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_") + "%"
            query = query.where(NvSaleOrder.email.ilike(term, escape="\\") |
                NvSaleOrder.parent_email.ilike(term, escape="\\") | NvSaleOrder.parent_note.ilike(term, escape="\\"))
        rows = session.exec(query.order_by(NvSaleOrder.sold_at.desc(), NvSaleOrder.id)).all()
        now = datetime.now(timezone.utc)
        refunds = refunds_for_orders(session, rows)
        receipts = [_receipt(row, now, refund=refunds.get(row.id)) for row in rows]
        return dict(items=[_public(row, now, refund=refunds.get(row.id)) for row in rows[(page - 1) * page_size:page * page_size]],
            total=len(rows), page=page, page_size=page_size,
            summary=dict(order_count=len(rows),
                effective_order_count=sum(item["status"] != "refunded" for item in receipts),
                refunded_count=sum(item["status"] == "refunded" for item in receipts),
                partial_refund_count=sum(item["status"] == "partial_refund" for item in receipts),
                received_count=sum(_received(item) for item in receipts),
                pending_warranty_count=sum(_pending(item) for item in receipts),
                recorded_revenue_yuan=_money(sum(item["revenue_cents"] or 0 for item in receipts)),
                unpriced_count=sum(_received(item) and item["revenue_cents"] is None
                    for item in receipts)))


def _revision(session, kind, key, before, after):
    session.add(NvFinanceRevision(entity_type=kind, entity_id=str(key),
        before_json=json.dumps(before, ensure_ascii=False), after_json=json.dumps(after, ensure_ascii=False)))


def update_order_finance(order_id, version, revenue_yuan, finance_note=""):
    cents, note = parse_money(revenue_yuan), _note(finance_note)
    if type(version) is not int or version < 0:
        raise ValueError("版本无效")
    with _store().transaction() as session:
        row = session.get(NvSaleOrder, order_id)
        if row is None:
            raise KeyError(order_id)
        if version != row.version:
            raise RuntimeError("记录已更新，请刷新后重试")
        before = dict(revenue_cents=row.revenue_cents, finance_note=row.finance_note, version=row.version)
        row.revenue_cents, row.finance_note = cents, note
        row.revenue_source = "manual" if cents is not None else "unknown"
        row.version += 1
        row.updated_at = time.time()
        session.add(row)
        _revision(session, "order_receipt", row.id, before,
                  dict(revenue_cents=cents, finance_note=note, version=row.version))
        return _public(row)


def create_manual_settlement(job_id, *, version, revenue_yuan, finance_note="",
                             sold_at=None, left_at=None):
    """Create an auditable receipt for a manually sold, released 5X child.

    No NV evidence is fabricated and no remote call is made. The operator must
    provide the amount; omitted timestamps use the membership's durable
    ``ended_at`` as a conservative historical anchor.
    """
    cents = parse_money(revenue_yuan)
    if cents is None:
        raise ValueError("人工结账必须填写实际售价")
    note = _note(finance_note)
    if not isinstance(job_id, str) or not job_id.strip():
        raise ValueError("任务编号无效")
    if type(version) is not int or version < 0:
        raise ValueError("任务版本无效")

    def parse_time(value, label):
        if value is None or value == "":
            return None
        if not isinstance(value, str):
            raise ValueError(f"{label}格式无效")
        result = _date(value)
        if result is None:
            raise ValueError(f"{label}格式无效")
        return result

    requested_sold = parse_time(sold_at, "售出时间")
    requested_left = parse_time(left_at, "退出时间")
    from core.db import GptBusinessChildMembershipModel as Membership
    store = _store()
    with store.transaction() as session:
        job = session.get(store.NvAutomationJob, job_id.strip())
        if job is None:
            raise KeyError(job_id)
        if job.version != version:
            raise RuntimeError("任务状态已更新，请刷新后重试")
        if job.seat_type != "prolite":
            raise RuntimeError("人工结账只适用于 5X 账号")
        if session.exec(select(NvSaleOrder).where(NvSaleOrder.job_id == job.id)).first() is not None:
            raise RuntimeError("该任务已经有结账记录")
        member = session.get(Membership, job.membership_id) if job.membership_id else None
        if member is None or member.ended_at is None:
            raise RuntimeError("未确认账号已退出母号空间")
        if (str(member.email or "").strip().casefold() != str(job.email or "").strip().casefold()
                or member.business_account_id != job.source_account_id
                or member.pro_account_id != job.child_id):
            raise RuntimeError("成员身份与任务记录不一致")
        ended = member.ended_at.replace(tzinfo=timezone.utc) if member.ended_at.tzinfo is None else member.ended_at.astimezone(timezone.utc)
        sold = requested_sold or ended
        left = requested_left or ended
        now = datetime.now(timezone.utc)
        if sold > left or left > now + timedelta(minutes=5):
            raise ValueError("售出/退出时间顺序或范围无效")
        catalog = _mother_catalog(session, [job.parent_account_id]).get(job.parent_account_id, {})
        parent_note = (catalog.get("note", "")
                       if catalog.get("email", "").casefold() == job.parent_email.casefold() else "")
        order = NvSaleOrder(
            sale_key="manual-" + job.id,
            job_id=job.id,
            parent_account_id=job.parent_account_id,
            source_account_id=job.source_account_id,
            parent_email=job.parent_email.strip(),
            parent_note=parent_note,
            child_id=job.child_id,
            email=job.email.strip().lower(),
            membership_id=job.membership_id,
            seat_type="prolite",
            sold_at=_iso(sold),
            left_at=_iso(left),
            listing_price_cents=cents,
            revenue_cents=cents,
            revenue_source="manual",
            finance_note=note,
        )
        session.add(order)
        session.flush()
        _revision(session, "manual_order_settlement", order.id, {},
                  dict(job_id=job.id, email=order.email, sold_at=order.sold_at,
                       left_at=order.left_at, revenue_cents=cents,
                       revenue_source="manual"))
        return _public(order)


def _profit_rows(session, now=None):
    store = _store()
    now = now or datetime.now(timezone.utc)
    today_start = now.astimezone(_REVENUE_TIMEZONE).replace(hour=0, minute=0, second=0, microsecond=0)
    today_end = today_start + timedelta(days=1)
    orders = session.exec(select(NvSaleOrder)).all()
    refunds = refunds_for_orders(session, orders)
    costs = {row.parent_account_id: row for row in session.exec(select(NvMotherCost)).all()}
    settings = store._settings(session.get(store.NvAutomationSettings, 1))
    ids = set(settings["mother_ids"]) | {row.parent_account_id for row in orders} | set(costs)
    catalog = _mother_catalog(session, ids)
    grouped = {}
    for parent_id in sorted(ids):
        historical = next((row for row in orders if row.parent_account_id == parent_id), None)
        cost = costs.get(parent_id)
        email = historical.parent_email if historical else (cost.parent_email if cost else catalog.get(parent_id, {}).get("email", ""))
        if not email:
            continue
        note = historical.parent_note if historical else (cost.parent_note if cost else "")
        if catalog.get(parent_id, {}).get("email", "").casefold() == email.casefold():
            note = catalog[parent_id]["note"]
        grouped[parent_id] = dict(parent_account_id=parent_id, parent_email=email, parent_note=note,
            is_dead=catalog.get(parent_id, {}).get("is_dead", False)
                if catalog.get(parent_id, {}).get("email", "").casefold() == email.casefold() else False,
            dead_detected_at=catalog.get(parent_id, {}).get("dead_detected_at")
                if catalog.get(parent_id, {}).get("email", "").casefold() == email.casefold() else None,
            order_count=0, closed_count=0, received_count=0, pending_warranty_count=0,
            effective_order_count=0, refunded_count=0, partial_refund_count=0,
            unpriced_count=0, revenue_cents=0,
            today_received_count=0, today_unpriced_count=0, today_revenue_cents=0,
            cost_cents=cost.cost_cents if cost else None, cost_note=cost.cost_note if cost else "",
            cost_version=cost.version if cost else 0)
    for row in orders:
        mother = grouped[row.parent_account_id]
        receipt = _receipt(row, now, refund=refunds.get(row.id))
        mother["order_count"] += 1
        mother["effective_order_count"] += receipt["status"] != "refunded"
        mother["refunded_count"] += receipt["status"] == "refunded"
        mother["partial_refund_count"] += receipt["status"] == "partial_refund"
        mother["closed_count"] += bool(row.left_at)
        mother["received_count"] += _received(receipt)
        mother["pending_warranty_count"] += _pending(receipt)
        mother["unpriced_count"] += _received(receipt) and receipt["revenue_cents"] is None
        mother["revenue_cents"] += receipt["revenue_cents"] or 0
        # Attribute receipts to the frozen warranty deadline, including when an
        # operator corrects the amount on a later day. Reads never book revenue.
        received_at = _date(receipt["received_at"])
        if _received(receipt) and received_at and today_start <= received_at < today_end:
            mother["today_received_count"] += 1
            mother["today_unpriced_count"] += receipt["revenue_cents"] is None
            mother["today_revenue_cents"] += receipt["revenue_cents"] or 0
    return list(grouped.values())


def _public_profit(row):
    result = {key: value for key, value in row.items() if not key.endswith("_cents")}
    result.update(recorded_revenue_yuan=_money(row["revenue_cents"]), cost_yuan=_money(row["cost_cents"]),
        today_revenue_yuan=_money(row["today_revenue_cents"]),
        profit_yuan=_money(row["revenue_cents"] - row["cost_cents"])
        if row["cost_cents"] is not None and row["unpriced_count"] == 0 else None)
    return result


def list_profits(q=""):
    now = datetime.now(timezone.utc)
    with Session(_store().engine) as session:
        term = q.strip().casefold()
        rows = [row for row in _profit_rows(session, now) if not term or
                term in row["parent_email"].casefold() or term in row["parent_note"].casefold()]
        missing_costs = sum(row["cost_cents"] is None for row in rows)
        unpriced = sum(row["unpriced_count"] for row in rows)
        revenue = sum(row["revenue_cents"] for row in rows)
        cost = sum(row["cost_cents"] or 0 for row in rows) if not missing_costs else None
        return dict(items=[_public_profit(row) for row in rows], summary=dict(
            order_count=sum(row["order_count"] for row in rows),
            effective_order_count=sum(row["effective_order_count"] for row in rows),
            refunded_count=sum(row["refunded_count"] for row in rows),
            partial_refund_count=sum(row["partial_refund_count"] for row in rows),
            received_count=sum(row["received_count"] for row in rows),
            pending_warranty_count=sum(row["pending_warranty_count"] for row in rows),
            unpriced_count=unpriced,
            today_received_count=sum(row["today_received_count"] for row in rows),
            today_unpriced_count=sum(row["today_unpriced_count"] for row in rows),
            today_revenue_yuan=_money(sum(row["today_revenue_cents"] for row in rows)),
            revenue_timezone=_REVENUE_TIMEZONE.tzname(None),
            revenue_date=now.astimezone(_REVENUE_TIMEZONE).date().isoformat(),
            recorded_revenue_yuan=_money(revenue), cost_yuan=_money(cost),
            profit_yuan=_money(revenue - cost) if cost is not None and not unpriced else None,
            unrecorded_cost_count=missing_costs))


def update_mother_cost(parent_account_id, version, cost_yuan, cost_note=""):
    cents, note = parse_money(cost_yuan), _note(cost_note)
    if type(version) is not int or version < 0:
        raise ValueError("版本无效")
    with _store().transaction() as session:
        mother = next((row for row in _profit_rows(session) if row["parent_account_id"] == parent_account_id), None)
        if mother is None:
            raise KeyError(parent_account_id)
        row = session.get(NvMotherCost, parent_account_id)
        if version != (row.version if row else 0):
            raise RuntimeError("记录已更新，请刷新后重试")
        if row is None:
            row = NvMotherCost(parent_account_id=parent_account_id, parent_email=mother["parent_email"], parent_note=mother["parent_note"])
        before = dict(cost_cents=row.cost_cents, cost_note=row.cost_note, version=row.version)
        row.cost_cents, row.cost_note = cents, note
        row.version += 1
        row.updated_at = time.time()
        session.add(row)
        _revision(session, "mother_cost", parent_account_id, before,
                  dict(cost_cents=cents, cost_note=note, version=row.version))
        mother.update(cost_cents=cents, cost_note=note, cost_version=row.version)
        return _public_profit(mother)
